name: cItems
version: 1.8
author: CyberCraft Studio
authors: [Mr_maderator_YT, Sarah_Fox, ssokeer]
main: com.ccs.citems.Main
api-version: 1.14
commands:
  items:
    description: Open a gui with items
    usage: /<command>
    permission: citems.gui




#Updates
#1.0 - creating plugin with one item
#1.1 -  fixed bug, called error:java.lang.NullPointerException
#1.2 - add damage resistance
#1.3 - add permissions
#1.3.1 - fixed bugs with messages and permissions
#1.4 - add gui menu
#1.4.1 - fixed bugs with enabling a plugin
#1.4.2 - fixed bugs with events
#1.4.3 - fixed bugs with gui
#1.4.4 - fixed bugs with commands
#1.4.5 - fixed bugs with location of item
#1.4.6 - fixed massages in console and add title of gui
#1.4.7 - fixed bugs with gui title
#1.4.8 - fixed bug with message in chat
#1.5 - add new item - pickaxe of doubling
#1.5.1 - fixed bugs with pickaxe of doubling
#1.5.2 - fixed bugs with explosion
#1.5.3 - fixed bugs with enabling plugin
#1.5.4 - fixed error with giving items in inventory
#1.5.5 - fixed bugs with drops using pickaxe
#1.5.5.1 - fixed bugs with name of pickaxe
#1.5.5.2 - fixed bugs with dropping
#1.6 - add new item - helmet of power
#1.6.1 - fixed error with registering element
#1.7 - adding permission for items, optimisation added, fixed drops for pickaxe of doubling
#1.8 - fixed bugs from helmet, witch didn`t gave effects and added new item - hoe
#1.9 - added hoe witch can remove chunks
#1.9.1 - remove hoe into boots witch can fly
